export const testTreeData = [{
  id: 1623,
  name: "分类",
  desc: "",
  parentId: 0,
  children: [
    {
      id: 2845,
      name: "场景模块",
      desc: "",
      parentId: 1623,
      children: [
        {
          id: 2846,
          name: "场景执行",
          desc: "",
          parentId: 2845,
          children: null,
          slots: {
            icon: "icon",
          },
          count: 4,
          entityId: 0,
        },
        {
          id: 2847,
          name: "编排节点",
          desc: "",
          parentId: 2845,
          children: null,
          slots: {
            icon: "icon",
          },
          count: 9,
          entityId: 0,
        },
        {
          id: 2848,
          name: "场景报告",
          desc: "",
          parentId: 2845,
          children: null,
          slots: {
            icon: "icon",
          },
          count: 4,
          entityId: 0,
        },
        {
          id: 2849,
          name: "处理器",
          desc: "",
          parentId: 2845,
          children: null,
          slots: {
            icon: "icon",
          },
          count: 3,
          entityId: 0,
        },
        {
          id: 2850,
          name: "场景调试",
          desc: "",
          parentId: 2845,
          children: null,
          slots: {
            icon: "icon",
          },
          count: 2,
          entityId: 0,
        },
      ],
      slots: {
        icon: "icon",
      },
      count: 34,
      entityId: 0,
    },
    {
      id: 2864,
      name: "设计器",
      desc: "",
      parentId: 1623,
      children: [
        {
          id: 2865,
          name: "接口用例",
          desc: "",
          parentId: 2864,
          children: null,
          slots: {
            icon: "icon",
          },
          count: 8,
          entityId: 0,
        },
        {
          id: 2866,
          name: "接口",
          desc: "",
          parentId: 2864,
          children: null,
          slots: {
            icon: "icon",
          },
          count: 2,
          entityId: 0,
        },
        {
          id: 2867,
          name: "标签",
          desc: "",
          parentId: 2864,
          children: null,
          slots: {
            icon: "icon",
          },
          count: 1,
          entityId: 0,
        },
      ],
      slots: {
        icon: "icon",
      },
      count: 27,
      entityId: 0,
    },
    {
      id: 2868,
      name: "服务管理",
      desc: "",
      parentId: 1623,
      children: [
        {
          id: 2869,
          name: "schema",
          desc: "",
          parentId: 2868,
          children: null,
          slots: {
            icon: "icon",
          },
          count: 8,
          entityId: 0,
        },
        {
          id: 2870,
          name: "版本",
          desc: "",
          parentId: 2868,
          children: null,
          slots: {
            icon: "icon",
          },
          count: 5,
          entityId: 0,
        },
        {
          id: 2871,
          name: "授权",
          desc: "",
          parentId: 2868,
          children: [
            {
              id: 1478,
              name: "删除项目成员",
              comments: "",
              method: ["POST"],
              parentId: 1477,
              scenarioId: 127,
              projectId: 10,
              useId: 0,
              entityCategory: "processor_interface",
              entityType: "processor_interface_default",
              entityId: 1184,
              endpointInterfaceId: 8977233,
              ordr: 0,
              children: null,
              slots: {
                icon: "icon",
              },
              isDir: false,
              entityRaw: null,
              result: null,
              processorInterfaceSrc: "define",
              round: "",
              entity: {
                id: 0,
                name: "",
                comments: "",
                default: "",
                processorID: 0,
                processorCategory: "",
                processorType: "",
                parentID: 0,
              },
              disable: false,
            },
            {
              id: 1479,
              name: "申请项目成员",
              comments: "",
              method: ["POST"],
              parentId: 1477,
              scenarioId: 127,
              projectId: 10,
              useId: 0,
              entityCategory: "processor_interface",
              entityType: "processor_interface_default",
              entityId: 1185,
              endpointInterfaceId: 8977246,
              ordr: 1,
              children: null,
              slots: {
                icon: "icon",
              },
              isDir: false,
              entityRaw: null,
              result: null,
              processorInterfaceSrc: "define",
              round: "",
              entity: {
                id: 0,
                name: "",
                comments: "",
                default: "",
                processorID: 0,
                processorCategory: "",
                processorType: "",
                parentID: 0,
              },
              disable: false,
            },
            {
              id: 1480,
              name: "获取用户参与的项目",
              comments: "",
              method: ["GET", "POST", "OPTIONS", "TRACE"],
              parentId: 1477,
              scenarioId: 127,
              projectId: 10,
              useId: 0,
              entityCategory: "processor_interface",
              entityType: "processor_interface_default",
              entityId: 1186,
              endpointInterfaceId: 8977346,
              ordr: 2,
              children: null,
              slots: {
                icon: "icon",
              },
              isDir: false,
              entityRaw: null,
              result: null,
              processorInterfaceSrc: "define",
              round: "",
              entity: {
                id: 0,
                name: "",
                comments: "",
                default: "",
                processorID: 0,
                processorCategory: "",
                processorType: "",
                parentID: 0,
              },
              disable: false,
            },
          ],
          slots: {
            icon: "icon",
          },
          count: 3,
          entityId: 0,
        },
      ],
      slots: {
        icon: "icon",
      },
      count: 26,
      entityId: 0,
    },
  ],
  slots: {
    icon: "icon",
  },
  count: 700,
  entityId: 0,
}];
